int _putchar(char c);
void print_array(int *a, int n);
void puts2(char *str);
void rev_string(char *s);
void puts_half(char *str);
int _atoi(char *s);
int _strcmp(char *s1, char *s2);
void reverse_array(int *a, int n);
char *string_toupper(char *);
char *cap_string(char *);
char *leet(char *);
char *_strncpy(char *dest, char *src, int n);
char *_memset(char *s, char b, unsigned int n);
char *_memcpy(char *dest, char *src, unsigned int n);
char *_strchr(char *s, char c);
